stages:
  - analysis
  - test
  - docs
  - deploy
  
cppcheck:
    stage: analysis
    image: ubuntu:bionic
    before_script:
        - apt update
        - apt install -y --no-install-recommends cppcheck
        - cppcheck --version
    script:
        - cppcheck src/ --verbose --enable=all --inconclusive --language=c++ --suppress=missingIncludeSystem --error-exitcode=1

test:
    stage: test
    image: conanio/gcc9
    before_script:
        - sudo apt update
        - sudo apt install -y --no-install-recommends valgrind gcovr=4.1-2
        - pip3 install --user gcovr==4.1
    script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug -DWITH_COVERAGE=ON
        - cmake --build .
        - cmake --build . --target test
        - ctest -T memcheck
        - cmake --build . --target coverage
    artifacts:
      paths:
        - build/coverage/

doxygen:
    stage: docs
    image: alpine:3.7
    before_script:
        - apk update
        - apk add --no-cache -t required_apks doxygen
        - mkdir -p build/docs
    script:
        - doxygen docs/Doxyfile
        - mv documentation/html/ public/
    artifacts:
        paths:
            - public/

build-package:
    stage: deploy
    image: conanio/gcc9
    before_script:
        - sudo apt update
        - sudo apt install -y --no-install-recommends curl
    script:
        - mkdir build-release
        - cd build-release
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF
        - cmake --build .
        - cpack -G DEB .
    artifacts:
        paths:
            - build-release/*.deb
