cppcheck:
    image: ubuntu:bionic
    before_script:
        - apt update
        - apt install -y --no-install-recommends cppcheck
        - cppcheck --version
    script:
        - cppcheck src/*.cpp --verbose --enable=all --inconclusive --

clang-tidy:
    image: base/archlinux:2018.09.01
    variables:
        CC: clang
        CXX: clang++
    before_script:
        - pacman -Syu --needed --noconfirm clang-tools-extra
        - clang-tidy --version
    script:
        - clang-tidy -warnings-as-errors="*" -checks="-*,clang-analyze"

doxygen:
    image: alpine:3.7
    before_script:
        - apk update
        - apk add --no-cache -t required_apks doxygen
        - mkdir -p build/docs
    script:
        - doxygen docs/Doxygile
    artifacts:
        paths:
            - build/docs/html
            
build-gcc7:
    image: conanio/gcc9
    before_script:
        - sudo apt update
        - sudo apt install gcovr
    script:
        - mkdir -b build
        - cd build
        - cmake ..
        - cmake --build .
        - cmake --build . --target test
        - cmake --build . --target memcheck
        - cmake --build . --target coverage
    artifacts:
        paths:
            - build/coverage/
            
deploy:
    image: conanio/gcc9
    before_script:
        - sudo apt update
        - sudo apt install -y --no-install-recommends curl
    script:
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF
        - cmake --build .
        - cpack -G DEB .
    artifacts:
        paths:
            - build/*.deb
