cppcheck:
    image: ubuntu:bionic
    before_script:
        - apt update
        - apt install -y --no-install-recommends cppcheck
        - cppcheck --version
    script:
        - cppcheck src/ --verbose --enable=all --inconclusive

doxygen:
    image: alpine:3.7
    before_script:
        - apk update
        - apk add --no-cache -t required_apks doxygen
        - mkdir -p build/docs
    script:
        - doxygen docs/Doxyfile
        - mv documentation/html/ public/
    artifacts:
        paths:
            - public/
            
build-gcc7:
    image: conanio/gcc9
    before_script:
        - sudo apt update
        - sudo apt install -y --no-install-recommends gcovr
    script:
        - mkdir build
        - cd build
        - cmake ..
        - cmake --build .
        - cmake --build . --target test
        - cmake --build . --target memcheck
        - cmake --build . --target coverage
    artifacts:
        paths:
            - build/coverage/
            
deploy:
    image: conanio/gcc9
    before_script:
        - sudo apt update
        - sudo apt install -y --no-install-recommends curl
    script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF
        - cmake --build .
        - cpack -G DEB .
    artifacts:
        paths:
            - build/*.deb
